Globomantics/Controllers/ConferenceController.cs
using System;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using Shared;

namespace Globomantics.Controllers
{
    public class ConferenceController:Controller
    {
        private readonly IConferenceService conferenceService;
        public ConferenceController(IConferenceService conferenceService)
        {
            this.conferenceService = conferenceService;
        }
        public async Task<ActionResult> Index()
        {
            ViewBag.Title = "Conferences";
            return View(await conferenceService.GetAll());
        }

        public IActionResult Add()
        {
            ViewBag.Title = "Add Conference";
            return View(new ConferenceModel());
        }
        [HttpPost]
        public async Task<ActionResult> Add(ConferenceModel model)
        {
            if (ModelState.IsValid)
            {
                await conferenceService.Add(model);
            }
            return RedirectToAction("Index");
        }
    }
}

Globomantics/Controllers/ProposalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using Shared;

namespace Globomantics.Controllers
{
    public class ProposalController : Controller
    {
        private readonly IConferenceService conferenceService;
        private readonly IProposalService proposalService;
        public ProposalController(IConferenceService conferenceService, IProposalService proposalService)
        {
            this.proposalService = proposalService;
            this.conferenceService = conferenceService;
        }
        public async Task<IActionResult> Index(int conferenceId)
        {
            var conference = await conferenceService.GetById(conferenceId);
            ViewBag.Title = $"Proposals for conference {conference.Name} {conference.Location}";
            ViewBag.ConferenceId = conferenceId;
            return View(await proposalService.GetAll(conferenceId));
        }

        public IActionResult Add(int conferenceId)
        {
            ViewBag.Title = "Add Proposal";
            return View(new ProposalModel { ConferenceId = conferenceId });
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProposalModel proposal)
        {
            if (ModelState.IsValid)
                await proposalService.Add(proposal);
            return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
        }

        public async Task<IActionResult> Approve(int proposalId)
        {
            var proposal = await proposalService.Approve(proposalId);
            return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
        }
    }
}

Globomantics/Views/Conference/DisplayTemplates/ConferenceModel.cshtml
@model Shared.ConferenceModel
<tr>
    <td>@Model.Name</td>
    <td>@Model.Location</td>
    <td>@Model.Start.ToString("ddd d MMM")</td>
    <td>@Model.AttendeeTotal</td>
    <td>
        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@Model.Id">Proposals</a>
    </td>
</tr>

Globomantics/Views/Conference/Index.cshtml
@using Shared;
@model IEnumerable<ConferenceModel>

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-4">
        <a asp-action="Add">Add</a>
    </div>
</div>

Globomantics/Views/Proposal/DisplayTemplates/ProposalModel.cshtml
@model Shared.ProposalModel
<tr>
    <td>@Model.Title</td>
    <td>@Model.Speaker</td>
    <td>
        @if(Model.Approved)
        {
            <div>Yes</div>
        }

        @if(!Model.Approved)
        {
            <a asp-action="Approve" asp-route-proposalId="@Model.Id">Approve</a>
        }
    </td>
</tr>

Globomantics/Views/Proposal/Index.cshtml
@using Shared
@model IEnumerable<ProposalModel>
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Speaker</th>
                <th>Approved</th>
                <th>Actions</th>
            </tr>
            @Html.DisplayForModel()
        </table>
        <a asp-action="Add" asp-route-conferenceId="@ViewBag.ConferenceId">Add</a>
    </div>
</div>

Globomantics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="css/*" asp-href-exclude="css/all.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="css/all.min.css" />
    </environment>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img asp-append-version="true" alt="logo" src="~/img/Globo_logo.png" />
            </div>
            <div class="col-md-10 titlecol">
                <span class="title">@ViewBag.Title</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>